/**
 * Writes db/schema.sql from whatever the target database currently contains.
 *
 *   node scripts/dump-schema.mjs                 # from the dev database
 *   DATABASE_TARGET=production node scripts/dump-schema.mjs
 *
 * Reads only. It exists because the schema for six of this project's tables lived
 * nowhere: `products`, `users`, `categories`, `product_categories`,
 * `contact_messages` and `orders` were created out of band, and the only DDL in
 * the repo was the handful of ALTER statements from later migrations. A database
 * you cannot recreate is a database you cannot restore, however good the backups
 * are — you would be restoring into a shape nobody has written down.
 *
 * Generated rather than hand-written so it cannot drift: re-run it after any
 * migration and commit the diff. `scripts/verify-schema.mjs` proves the output
 * actually rebuilds the same shape.
 *
 * Emitted in two passes — every table, then every foreign key — so the file has
 * no ordering requirements and can be replayed top to bottom into an empty
 * database.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { ROOT, connect, describeTarget } from "./lib/db.mjs";

const sql = connect();
const SAFE_IDENT = /^[a-z_][a-z0-9_]*$/;

/** Quotes an identifier only when it needs it, so the output stays readable. */
const ident = (name) => (SAFE_IDENT.test(name) ? name : JSON.stringify(name));

const tables = (
  await sql`
    SELECT c.relname AS name
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind = 'r'
    ORDER BY c.relname
  `
).map((r) => r.name);

for (const name of tables) {
  if (!SAFE_IDENT.test(name)) {
    throw new Error(`refusing to dump unexpected table name: ${name}`);
  }
}

/**
 * Sequences have to be created before the tables that default to nextval() on
 * them, and handed back to those columns afterwards so a DROP TABLE takes the
 * sequence with it. Missing these is not a cosmetic gap: three of this project's
 * tables default to a sequence, so a schema file without them fails on the very
 * first CREATE TABLE against an empty database — which is precisely the case the
 * file exists for. verify-schema.mjs is what caught it.
 */
const sequences = await sql`
  SELECT s.relname AS name,
         seq.seqstart AS start,
         seq.seqincrement AS increment,
         seq.seqmin AS minimum,
         seq.seqmax AS maximum,
         seq.seqcache AS cache,
         seq.seqcycle AS cycle,
         format_type(seq.seqtypid, NULL) AS type,
         owner.relname AS owned_table,
         a.attname AS owned_column
  FROM pg_class s
  JOIN pg_namespace n ON n.oid = s.relnamespace
  JOIN pg_sequence seq ON seq.seqrelid = s.oid
  LEFT JOIN pg_depend d
    ON d.objid = s.oid AND d.classid = 'pg_class'::regclass AND d.deptype = 'a'
  LEFT JOIN pg_class owner ON owner.oid = d.refobjid
  LEFT JOIN pg_attribute a ON a.attrelid = d.refobjid AND a.attnum = d.refobjsubid
  WHERE n.nspname = 'public' AND s.relkind = 'S'
  ORDER BY s.relname
`;

const sequenceDdl = sequences.map((s) => {
  const bits = [
    `CREATE SEQUENCE IF NOT EXISTS ${ident(s.name)}`,
    `  AS ${s.type}`,
    `  INCREMENT BY ${s.increment}`,
    `  MINVALUE ${s.minimum}`,
    `  MAXVALUE ${s.maximum}`,
    `  START WITH ${s.start}`,
    `  CACHE ${s.cache}`,
    s.cycle ? "  CYCLE" : "  NO CYCLE",
  ];
  return `${bits.join("\n")};`;
});

const sequenceOwners = sequences
  .filter((s) => s.owned_table && s.owned_column)
  .map(
    (s) =>
      `ALTER SEQUENCE ${ident(s.name)} OWNED BY ${ident(s.owned_table)}.${ident(s.owned_column)};`
  );

const parts = [];
const foreignKeys = [];

for (const table of tables) {
  const columns = await sql`
    SELECT a.attname AS name,
           format_type(a.atttypid, a.atttypmod) AS type,
           a.attnotnull AS not_null,
           a.attidentity AS identity,
           pg_get_expr(d.adbin, d.adrelid) AS default_expr
    FROM pg_attribute a
    LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
    WHERE a.attrelid = ${`public.${table}`}::regclass
      AND a.attnum > 0 AND NOT a.attisdropped
    ORDER BY a.attnum
  `;

  const constraints = await sql`
    SELECT conname AS name, contype AS type, pg_get_constraintdef(oid) AS def
    FROM pg_constraint
    WHERE conrelid = ${`public.${table}`}::regclass
    ORDER BY contype, conname
  `;

  const lines = columns.map((c) => {
    let line = `  ${ident(c.name)} ${c.type}`;
    // An identity column carries its own generator; a DEFAULT would conflict.
    if (c.identity === "a") line += " GENERATED ALWAYS AS IDENTITY";
    else if (c.identity === "d") line += " GENERATED BY DEFAULT AS IDENTITY";
    else if (c.default_expr) line += ` DEFAULT ${c.default_expr}`;
    if (c.not_null) line += " NOT NULL";
    return line;
  });

  // Primary keys, uniques and checks belong in the table; foreign keys are held
  // back so the file needs no dependency ordering.
  for (const con of constraints) {
    if (con.type === "f") {
      foreignKeys.push(
        `ALTER TABLE ${ident(table)} ADD CONSTRAINT ${ident(con.name)} ${con.def};`
      );
      continue;
    }
    if (con.type === "p" || con.type === "u" || con.type === "c") {
      lines.push(`  CONSTRAINT ${ident(con.name)} ${con.def}`);
    }
  }

  parts.push(`CREATE TABLE IF NOT EXISTS ${ident(table)} (\n${lines.join(",\n")}\n);`);

  // Indexes that are not already implied by a constraint above.
  const constraintNames = new Set(constraints.map((c) => c.name));
  const indexes = await sql`
    SELECT indexname AS name, indexdef AS def
    FROM pg_indexes
    WHERE schemaname = 'public' AND tablename = ${table}
    ORDER BY indexname
  `;
  const extra = indexes
    .filter((i) => !constraintNames.has(i.name))
    .map((i) => `${i.def.replace(/^CREATE INDEX /, "CREATE INDEX IF NOT EXISTS ")};`);
  if (extra.length) parts.push(extra.join("\n"));
}

const header = `-- SHEMO PHARM — database schema
--
-- GENERATED FILE. Produced by scripts/dump-schema.mjs; do not edit by hand.
-- Re-run that script after a migration and commit the diff.
--
-- Replay top to bottom into an empty database to recreate the shape:
--   node scripts/apply-schema.mjs
-- Verify that it really does, against a throwaway Neon branch:
--   node scripts/verify-schema.mjs
--
-- Structure only — no rows. The catalogue is reseeded with \`npm run seed:db\`
-- from src/data/*.json; customer data comes from a backup, never from here.
--
-- Tables: ${tables.join(", ")}
`;

const section = (title, items) =>
  items.length ? [`-- ${title}`, items.join("\n")] : [];

const body = [
  header,
  ...section("Sequences, before the tables that default to them", sequenceDdl),
  ...parts,
  ...section("Sequence ownership, so DROP TABLE takes the sequence too", sequenceOwners),
  ...section("Foreign keys, last so the file needs no table ordering", foreignKeys),
]
  .join("\n\n")
  .replace(/\n{3,}/g, "\n\n");

mkdirSync(path.join(ROOT, "db"), { recursive: true });
const out = path.join(ROOT, "db", "schema.sql");
writeFileSync(out, `${body.trimEnd()}\n`, "utf8");

console.log(`${describeTarget()} -> db/schema.sql`);
console.log(`${tables.length} tables: ${tables.join(", ")}`);
console.log(`${sequences.length} sequences, ${foreignKeys.length} foreign keys`);
